### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by johbs** [blaisewf/RVC_CLI#62]
Can anyone help please:

I'm trying to generate a new pth and got follow error:

`"FileNotFoundError: [Errno 2] No such file or directory: '/home/user/RVC_CLI/logs/mute/sliced_audios/mute40000.wav'"
`
Step To get a error:

1.  Preprocess Dataset (ok in this step)
`python3 rvc.py preprocess --model_name "johnnyc" --dataset_path "../models/sample/" --sampling_rate "40000"
`
2. Extract Features (ok in this step)
`python3 rvc.py extract --model_name "johnnyc" --rvc_version "v2" --sampling_rate "40000"
`
3. Start Training
`python3 rvc.py train --model_name "johnnyc" --rvc_version "v2" --save_every_epoch "3" --sampling_rate "40000"
`
Got a follow error:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/RVC_CLI/rvc/train/train.py", line 215, in run
    train_dataset = TextAudioLoaderMultiNSFsid(hps.data)
  File "/home/user/RVC_CLI/rvc/train/data_utils.py", line 21, in __init__
    self._filter()
  File "/home/user/RVC_CLI/rvc/train/data_utils.py", line 29, in _filter
    lengths.append(os.path.getsize(audiopath) // (3 * self.hop_length))
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/RVC_CLI/logs/mute/sliced_audios/mute40000.wav'
Saved index file '/home/user/RVC_CLI/logs/johnnyc/added_IVF94_Flat_nprobe_1_v2.index'
```

**Comment by blaisewf** [comment]
try new update
